name: OWASP ZAP integration with github action
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applications
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Security Scan Action
        uses: TinyCrowsTesting/gh-tinycrows@v1.0.0
        with:
          target: "http://testphp.vulnweb.com/"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
